// Generated by CoffeeScript 1.4.0
(function() {
  var fs, k, model, models, v, _i, _len, _ref;

  fs = require('fs');

  models = ['_index', 'user', 'planning', 'group'];

  module.exports = [];

  for (_i = 0, _len = models.length; _i < _len; _i++) {
    model = models[_i];
    _ref = require("./" + model);
    for (k in _ref) {
      v = _ref[k];
      module.exports[k] = v;
    }
  }

}).call(this);
