// Generated by CoffeeScript 1.4.0
(function() {
  var Model,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('../Model').Model;

  module.exports.Planning = (function(_super) {

    __extends(Planning, _super);

    function Planning() {
      this.load = __bind(this.load, this);

      this.calendar = __bind(this.calendar, this);

      this.setupRoutes = __bind(this.setupRoutes, this);
      return Planning.__super__.constructor.apply(this, arguments);
    }

    Planning.prototype.setupRoutes = function() {
      this.router = {
        calendar: this.calendar,
        load: this.load
      };
      return this.globalRoutes['planning'] = this.router;
    };

    Planning.prototype.calendar = function(fn) {
      return this.request("planning/calendar/", fn);
    };

    Planning.prototype.load = function(fn) {
      return this.request("planning/load/", fn);
    };

    return Planning;

  })(Model);

}).call(this);
