// Generated by CoffeeScript 1.4.0
(function() {
  var Client;

  Client = (function() {

    function Client(opts) {
      var _base, _base1, _ref, _ref1;
      this.opts = opts != null ? opts : {};
      if ((_ref = (_base = this.opts).login) == null) {
        _base.login = '';
      }
      if ((_ref1 = (_base1 = this.opts).url) == null) {
        _base1.url = 'https://intra.epitech.bigint.fr/intra/';
      }
    }

    return Client;

  })();

  module.exports = {
    Client: Client
  };

}).call(this);
