// Generated by CoffeeScript 1.4.0
(function() {
  var models,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  models = require('./models');

  module.exports.Client = (function() {

    function Client(opts) {
      var _base, _base1, _ref, _ref1;
      this.opts = opts != null ? opts : {};
      this.initModels = __bind(this.initModels, this);

      this.initModel = __bind(this.initModel, this);

      if ((_ref = (_base = this.opts).login) == null) {
        _base.login = '';
      }
      if ((_ref1 = (_base1 = this.opts).url) == null) {
        _base1.url = 'https://intra.epitech.bigint.fr/intra/';
      }
      this.models = {};
      this.initModels();
      return this;
    }

    Client.prototype.initModel = function(cls) {
      var model;
      model = new cls(this);
      model.setupRoutes();
      model.attach();
      return model;
    };

    Client.prototype.initModels = function() {
      var k, v, _results;
      _results = [];
      for (k in models) {
        v = models[k];
        _results.push(this.models[k] = this.initModel(v));
      }
      return _results;
    };

    return Client;

  })();

}).call(this);
