// Generated by CoffeeScript 1.5.0
(function() {
  var Client, client;

  Client = require('..').Client;

  client = new Client({
    login: 'touron_m',
    password: 'xxxxx',
    url: 'https://intra.epitech.bigint.fr/intra/',
    auth_token: 'xxxxx-xxxxx-xxxxx-xxxxx',
    verbose: true
  });

  console.log(client);

}).call(this);
