// Generated by CoffeeScript 1.4.0
(function() {
  var Client, client;

  Client = require('..').Client;

  client = new Client({
    login: 'touron_m',
    url: 'https://intra.epitech.bigint.fr/intra/'
  });

  console.log(client);

}).call(this);
