// Generated by CoffeeScript 1.4.0
(function() {
  var Client, client;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Client = require('..').Client;

  client = new Client({
    verbose: true
  });

  client.user('touron_m').binome(function(err, data, binomes) {
    var binome;
    if (err) {
      return console.log(err, data, binomes);
    }
    return console.log([
      (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = binomes.length; _i < _len; _i++) {
          binome = binomes[_i];
          _results.push(binome.login);
        }
        return _results;
      })()
    ][0].join(', '));
  });

}).call(this);
