// Generated by CoffeeScript 1.4.0
(function() {
  var Client, client;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Client = require('..').Client;

  client = new Client({
    verbose: true
  });

  client.user('touron_m').netsoul.getlog(function(err, logs) {
    var log, _i, _len, _results;
    if (err) {
      return console.log(err, logs);
    }
    _results = [];
    for (_i = 0, _len = logs.length; _i < _len; _i++) {
      log = logs[_i];
      _results.push(console.log(log));
    }
    return _results;
  });

}).call(this);
