// Generated by CoffeeScript 1.4.0
(function() {
  var Client, client, obj, path, paths, _i, _len;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Client = require('..').Client;

  client = new Client({
    verbose: true
  });

  paths = ["client", "client.index", "client.user", "client.user.index", "client.user('touron_m')", "client.user('touron_m').index", "client.user('touron_m').binome"];

  for (_i = 0, _len = paths.length; _i < _len; _i++) {
    path = paths[_i];
    obj = eval(path);
    if (typeof obj === 'function') {
      obj(function(err, data) {
        return console.log("[+] path=" + path + ", err=" + err + ", data=" + data);
      });
    } else {
      console.error("[-] path=" + path + " is not a function");
    }
  }

}).call(this);
