// Generated by CoffeeScript 1.4.0
(function() {
  var Client, client, search_filters;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Client = require('..').Client;

  client = new Client({
    verbose: true
  });

  search_filters = {
    location: 'FR/PAR',
    year: '2011',
    active: false,
    offset: 0
  };

  client.user.filter.user(search_filters, function(err, items, result) {
    var item, _i, _len, _results;
    if (err) {
      return console.log(err, items);
    }
    console.log("Displaying: " + items.length + " / " + result.total);
    _results = [];
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      item = items[_i];
      _results.push(console.log(item.login));
    }
    return _results;
  });

}).call(this);
